# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hackeval-node-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm installing Dependencies
        run: |
          npm install
        working-directory: ./backend

      - name: Build Backend Server
        run: npm run start --if-present
        working-directory: ./backend

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-backend
          path: ./backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-backend
          path: ./artifact

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_C78AFE1ADAF14FFD9B89F6ED12055A84 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_962F6CA843B042A7AF28CC75986DBE79 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_EDBB2FA545CA453B9CA882F35BD73D9B }}

      - name: "Deploy to Azure Web App"
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: "hackeval-node-backend"
          slot-name: "Production"
          package: ./artifact/node-backend
